### ISSUE TITLE
ImageMagick now not have magick commands

### ISSUE THREAD

**Issue by bthkfahsun** [slhck/compress-pptx#9]
ImageMagick now not have "magick' commands
Now have "convert" commands

**Comment by slhck** [comment]
If I understand you correctly, you do not have the magick command on your system.

Since I don't know anything about your system (operating system, or how you installed Image Magick), I am unable to help. I recommend installing ImageMagick according to the instructions on its website. In any case, more details would be needed to troubleshoot this.

**Comment by Suzanaralu** [comment]
Hello, I installed Imagemagick in windows 11 but I am not able to see the desktop icon and when I use the cmd to try if magick works, an error appears.
magick: unable to open image 'wizard': No such file or directory @ error/blob.c/OpenBlob/3596.
magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

**Comment by slhck** [comment]
I cannot offer support for ImageMagick here — please try their discussion space: https://github.com/ImageMagick/ImageMagick/discussions
